DROP TABLE IF EXISTS lineorder;
DROP TABLE IF EXISTS supplier;
DROP TABLE IF EXISTS customer;
DROP TABLE IF EXISTS part;
DROP TABLE IF EXISTS date;

CREATE TABLE supplier (
	S_SUPPKEY	INT,
	S_NAME	CHAR(25),
	S_ADDRESS	VARCHAR(25),
	S_CITY		CHAR(10),
	S_NATION	CHAR(15),
	S_REGION	CHAR(12),
	S_PHONE	CHAR(15),
	PRIMARY KEY(S_SUPPKEY)
);
COPY supplier FROM '/Users/gimli/projects/fluent_joins/pdfg/output/SUPPLIER.tbl' WITH DELIMITER AS '|';

CREATE TABLE customer (
	C_CUSTKEY		INT,
	C_NAME		CHAR(25),
	C_ADDRESS		VARCHAR(25),
	C_CITY			CHAR(10),
	C_NATION		CHAR(15),
	C_REGION		CHAR(12),
	C_PHONE		CHAR(15),
	C_MKTSEGMENT	CHAR(10),
	PRIMARY KEY(C_CUSTKEY)
);
COPY customer FROM '/Users/gimli/projects/fluent_joins/pdfg/output/CUSTOMER.tbl' WITH DELIMITER AS '|';

CREATE TABLE part (
	P_PARTKEY	INT,
	P_NAME	VARCHAR(30),
	P_MFGR	CHAR(6),
	P_CATEGORY	CHAR(7),
	P_BRAND	CHAR(9),
	P_COLOR	VARCHAR(11),
	P_TYPE		VARCHAR(25),
	P_SIZE		INT,
	P_CONTAINER	CHAR(10),
	PRIMARY KEY(P_PARTKEY)
);
COPY part FROM '/Users/gimli/projects/fluent_joins/pdfg/output/PART.tbl' WITH DELIMITER AS '|';

CREATE TABLE date (
	D_DATEKEY			INT,
	D_DATE			CHAR(18),
	D_DAYOFWEEK			CHAR(10),
	D_MONTH			CHAR(9),
	D_YEAR			CHAR(4),
	D_YEARMONTHNUM		INT,
	D_YEARMONTH		CHAR(7),
	D_DAYNUMINWEEK		INT,
	D_DAYNUMINMONTH		INT,
	D_DAYNUMINYEAR		INT,
	D_MONTHNUMINYEAR 		INT,
	D_WEEKNUMINYEAR		INT,
	D_SELLINGSEASON		CHAR(12),
	D_LASTDAYINWEEKFL		BOOLEAN,
	D_LASTDAYINMONTHFL	BOOLEAN,
	D_HOLIDAYFL			BOOLEAN,
	D_WEEKDAYFL			BOOLEAN,
	PRIMARY KEY(D_DATEKEY)
);
COPY date FROM '/Users/gimli/projects/fluent_joins/pdfg/output/DATE.tbl' WITH DELIMITER AS '|';

CREATE TABLE lineorder (
	LO_ORDERKEY			INT,
	LO_LINENUMBER		INT,
	LO_CUSTKEY			INT,
	LO_PARTKEY			INT,
	LO_SUPPKEY			INT,
	LO_ORDERDATE		INT,
	LO_ORDERPRIORITY		CHAR(15),
	LO_SHIPPRIORITY		CHAR(1),
	LO_QUANTITY			INT,
	LO_EXTENDEDPRICE		NUMERIC,
	LO_ORDTOTALPRICE 		NUMERIC,
	LO_DISCOUNT			NUMERIC,
	LO_REVENUE			NUMERIC,
	LO_SUPPLYCOST		NUMERIC,
	LO_TAX			INT,
	LO_COMMITDATE		INT,
	LO_SHIPMODE			CHAR(10),
	PRIMARY KEY(LO_ORDERKEY, LO_LINENUMBER)
);
COPY lineorder FROM '/Users/gimli/projects/fluent_joins/pdfg/output/LINEORDER.tbl' WITH DELIMITER AS '|';